name: food_app
version: 1.0.0+1
description: Food App
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  animated_splash_screen: ^1.1.0
  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: app_icon_round
  image_path: icons/app_icon_round.png
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

