name: food_app
version: 1.0.0+1
description: Food App
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  cached_network_image: ^3.2.0
  auto_size_text: 3.0.0
  animated_splash_screen: ^1.1.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.13
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: app_icon_round
  image_path: icons/app_icon_round.png
  ios: true

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

